using ConceptualMath.Numbers.Generation;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Linq;
using System.Numerics;

namespace ProjectEulerSolutions
{
    [TestClass]
    public class Problem0002
    {
        /*
        Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

        By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
        */

        private BigInteger Answer => 4613732;

        [TestMethod]
        public void SumOfFibonacci_WithValuesLE89_IsSomething()
        {
            var expected = new int[]
            {
                1, 2, 3, 5, 8, 13, 21, 34, 55, 89
            }.Sum();

            var actual = Sequences.FibonacciNumbers()
                .TakeWhile(fib => fib <= 89)
                .Sum();

            Assert.AreEqual(expected, actual);
        }

        [TestMethod]
        public void SumOfFibonacci_WithEvenValuesLE4Million_Is4613732()
        {
            var actual = Sequences.FibonacciNumbers()
                .TakeWhile(fib => fib <= 4000000)
                .Where(v => v % 2 == 0)
                .Sum();

            Assert.AreEqual(Answer, actual);
        }
    }
}
